backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "produk"
    label: "Produk"
    folder: "content/produk"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama Produk", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "body", widget: "markdown" }
      - { label: "Gambar", name: "image", widget: "image" }
