backend:
  name: git-gateway
  branch: main
  identity_url: https://tokogadgetonline.netlify.app/.netlify/identity

publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "produk"
    label: "Produk"
    folder: "content/produk"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "body", widget: "markdown" }
